/*
 * Copyright © 2011 Everit Kft. (http://www.everit.org)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-636312f2dc6e26921216979d4ae12655beeff255
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.everit.atlassian.restclient.jiracloud.v3.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.everit.atlassian.restclient.jiracloud.v3.model.IssueTransitionStatus;

/**
 * SimplifiedIssueTransition
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-31T17:15:41.549+02:00[Europe/Prague]")
public class SimplifiedIssueTransition {
  @JsonProperty("to")
  private IssueTransitionStatus to;

  @JsonProperty("transitionId")
  private Integer transitionId;

  @JsonProperty("transitionName")
  private String transitionName;

   /**
   * The issue status change of the transition.
   * @return to
  **/
  @ApiModelProperty(value = "The issue status change of the transition.")
  public IssueTransitionStatus getTo() {
    return to;
  }

   /**
   * The unique ID of the transition.
   * @return transitionId
  **/
  @ApiModelProperty(value = "The unique ID of the transition.")
  public Integer getTransitionId() {
    return transitionId;
  }

   /**
   * The name of the transition.
   * @return transitionName
  **/
  @ApiModelProperty(value = "The name of the transition.")
  public String getTransitionName() {
    return transitionName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SimplifiedIssueTransition simplifiedIssueTransition = (SimplifiedIssueTransition) o;
    return Objects.equals(this.to, simplifiedIssueTransition.to) &&
        Objects.equals(this.transitionId, simplifiedIssueTransition.transitionId) &&
        Objects.equals(this.transitionName, simplifiedIssueTransition.transitionName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(to, transitionId, transitionName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SimplifiedIssueTransition {\n");
    
    sb.append("    to: ").append(toIndentedString(to)).append("\n");
    sb.append("    transitionId: ").append(toIndentedString(transitionId)).append("\n");
    sb.append("    transitionName: ").append(toIndentedString(transitionName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

