/*
 * Copyright © 2011 Everit Kft. (http://www.everit.org)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.everit.atlassian.restclient.jiracloud.v3.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * The workflow scheme read request body.
 */
@ApiModel(description = "The workflow scheme read request body.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-11-13T15:26:43.813+01:00[Europe/Prague]")
public class WorkflowSchemeReadRequest {
  @JsonProperty("projectIds")
  private List<String> projectIds = new ArrayList<>();

  @JsonProperty("workflowSchemeIds")
  private List<String> workflowSchemeIds = new ArrayList<>();

  public WorkflowSchemeReadRequest projectIds(List<String> projectIds) {
    this.projectIds = projectIds;
    return this;
  }

  public WorkflowSchemeReadRequest addProjectIdsItem(String projectIdsItem) {
    if (this.projectIds == null) {
      this.projectIds = new ArrayList<>();
    }
    this.projectIds.add(projectIdsItem);
    return this;
  }

   /**
   * The list of project IDs to query.
   * @return projectIds
  **/
  @ApiModelProperty(value = "The list of project IDs to query.")
  public List<String> getProjectIds() {
    return projectIds;
  }

  public void setProjectIds(List<String> projectIds) {
    this.projectIds = projectIds;
  }

  public WorkflowSchemeReadRequest workflowSchemeIds(List<String> workflowSchemeIds) {
    this.workflowSchemeIds = workflowSchemeIds;
    return this;
  }

  public WorkflowSchemeReadRequest addWorkflowSchemeIdsItem(String workflowSchemeIdsItem) {
    if (this.workflowSchemeIds == null) {
      this.workflowSchemeIds = new ArrayList<>();
    }
    this.workflowSchemeIds.add(workflowSchemeIdsItem);
    return this;
  }

   /**
   * The list of workflow scheme IDs to query.
   * @return workflowSchemeIds
  **/
  @ApiModelProperty(value = "The list of workflow scheme IDs to query.")
  public List<String> getWorkflowSchemeIds() {
    return workflowSchemeIds;
  }

  public void setWorkflowSchemeIds(List<String> workflowSchemeIds) {
    this.workflowSchemeIds = workflowSchemeIds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WorkflowSchemeReadRequest workflowSchemeReadRequest = (WorkflowSchemeReadRequest) o;
    return Objects.equals(this.projectIds, workflowSchemeReadRequest.projectIds) &&
        Objects.equals(this.workflowSchemeIds, workflowSchemeReadRequest.workflowSchemeIds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(projectIds, workflowSchemeIds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WorkflowSchemeReadRequest {\n");
    
    sb.append("    projectIds: ").append(toIndentedString(projectIds)).append("\n");
    sb.append("    workflowSchemeIds: ").append(toIndentedString(workflowSchemeIds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

