/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.everit.atlassian.restclient.jiracloud.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.net.URI;

/**
 * Count of issues assigned to a component.
 */
@ApiModel(description = "Count of issues assigned to a component.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-09-01T13:56:58.037+02:00[Europe/Prague]")
public class ComponentIssuesCount {
  @JsonProperty("self")
  private URI self;

  @JsonProperty("issueCount")
  private Long issueCount;

   /**
   * The URL for this count of issues for a component.
   * @return self
  **/
  @ApiModelProperty(value = "The URL for this count of issues for a component.")
  public URI getSelf() {
    return self;
  }

   /**
   * The count of issues assigned to a component.
   * @return issueCount
  **/
  @ApiModelProperty(value = "The count of issues assigned to a component.")
  public Long getIssueCount() {
    return issueCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComponentIssuesCount componentIssuesCount = (ComponentIssuesCount) o;
    return Objects.equals(this.self, componentIssuesCount.self) &&
        Objects.equals(this.issueCount, componentIssuesCount.issueCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(self, issueCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComponentIssuesCount {\n");
    sb.append("    self: ").append(toIndentedString(self)).append("\n");
    sb.append("    issueCount: ").append(toIndentedString(issueCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

