/*
 * Copyright © 2011 Everit Kft. (http://www.everit.org)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-636312f2dc6e26921216979d4ae12655beeff255
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.everit.atlassian.restclient.jiracloud.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

/**
 * Details of changes to a priority scheme&#39;s priorities that require suggested priority mappings.
 */
@ApiModel(description = "Details of changes to a priority scheme's priorities that require suggested priority mappings.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-31T17:15:14.708+02:00[Europe/Prague]")
public class SuggestedMappingsForPrioritiesRequestBean {
  @JsonProperty("add")
  private List<Long> add = new ArrayList<>();

  @JsonProperty("remove")
  private List<Long> remove = new ArrayList<>();

  public SuggestedMappingsForPrioritiesRequestBean add(List<Long> add) {
    this.add = add;
    return this;
  }

  public SuggestedMappingsForPrioritiesRequestBean addAddItem(Long addItem) {
    if (this.add == null) {
      this.add = new ArrayList<>();
    }
    this.add.add(addItem);
    return this;
  }

   /**
   * The ids of priorities being removed from the scheme.
   * @return add
  **/
  @ApiModelProperty(value = "The ids of priorities being removed from the scheme.")
  public List<Long> getAdd() {
    return add;
  }

  public void setAdd(List<Long> add) {
    this.add = add;
  }

  public SuggestedMappingsForPrioritiesRequestBean remove(List<Long> remove) {
    this.remove = remove;
    return this;
  }

  public SuggestedMappingsForPrioritiesRequestBean addRemoveItem(Long removeItem) {
    if (this.remove == null) {
      this.remove = new ArrayList<>();
    }
    this.remove.add(removeItem);
    return this;
  }

   /**
   * The ids of priorities being removed from the scheme.
   * @return remove
  **/
  @ApiModelProperty(value = "The ids of priorities being removed from the scheme.")
  public List<Long> getRemove() {
    return remove;
  }

  public void setRemove(List<Long> remove) {
    this.remove = remove;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SuggestedMappingsForPrioritiesRequestBean suggestedMappingsForPrioritiesRequestBean = (SuggestedMappingsForPrioritiesRequestBean) o;
    return Objects.equals(this.add, suggestedMappingsForPrioritiesRequestBean.add) &&
        Objects.equals(this.remove, suggestedMappingsForPrioritiesRequestBean.remove);
  }

  @Override
  public int hashCode() {
    return Objects.hash(add, remove);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SuggestedMappingsForPrioritiesRequestBean {\n");
    
    sb.append("    add: ").append(toIndentedString(add)).append("\n");
    sb.append("    remove: ").append(toIndentedString(remove)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

