/*
 * Copyright © 2011 Everit Kft. (http://www.everit.org)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/*
 * The Jira Cloud platform REST API
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT-636312f2dc6e26921216979d4ae12655beeff255
 * Contact: ecosystem@atlassian.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.everit.atlassian.restclient.jiracloud.v2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.everit.atlassian.restclient.jiracloud.v2.model.ConditionGroupUpdate;
import org.everit.atlassian.restclient.jiracloud.v2.model.WorkflowRuleConfiguration;
import org.everit.atlassian.restclient.jiracloud.v2.model.WorkflowTransitionLinks;
import org.everit.atlassian.restclient.jiracloud.v2.model.WorkflowTrigger;

/**
 * The transition update data.
 */
@ApiModel(description = "The transition update data.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-03-31T17:15:14.708+02:00[Europe/Prague]")
public class TransitionUpdateDTO {
  @JsonProperty("actions")
  private List<WorkflowRuleConfiguration> actions = new ArrayList<>();

  @JsonProperty("conditions")
  private ConditionGroupUpdate conditions;

  @JsonProperty("customIssueEventId")
  private String customIssueEventId;

  @JsonProperty("description")
  private String description;

  @JsonProperty("id")
  private String id;

  @JsonProperty("links")
  private List<WorkflowTransitionLinks> links = new ArrayList<>();

  @JsonProperty("name")
  private String name;

  @JsonProperty("properties")
  private Map<String, String> properties = new HashMap<>();

  @JsonProperty("toStatusReference")
  private String toStatusReference;

  @JsonProperty("transitionScreen")
  private WorkflowRuleConfiguration transitionScreen;

  @JsonProperty("triggers")
  private List<WorkflowTrigger> triggers = new ArrayList<>();

  /**
   * The transition type.
   */
  public enum TypeEnum {
    INITIAL("INITIAL"),
    
    GLOBAL("GLOBAL"),
    
    DIRECTED("DIRECTED");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equalsIgnoreCase(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  @JsonProperty("type")
  private TypeEnum type;

  @JsonProperty("validators")
  private List<WorkflowRuleConfiguration> validators = new ArrayList<>();

  private HashMap<String, Object> additionalProperties_ = new HashMap<String, Object>();

  public TransitionUpdateDTO actions(List<WorkflowRuleConfiguration> actions) {
    this.actions = actions;
    return this;
  }

  public TransitionUpdateDTO addActionsItem(WorkflowRuleConfiguration actionsItem) {
    if (this.actions == null) {
      this.actions = new ArrayList<>();
    }
    this.actions.add(actionsItem);
    return this;
  }

   /**
   * The post-functions of the transition.
   * @return actions
  **/
  @ApiModelProperty(value = "The post-functions of the transition.")
  public List<WorkflowRuleConfiguration> getActions() {
    return actions;
  }

  public void setActions(List<WorkflowRuleConfiguration> actions) {
    this.actions = actions;
  }

  public TransitionUpdateDTO conditions(ConditionGroupUpdate conditions) {
    this.conditions = conditions;
    return this;
  }

   /**
   * Get conditions
   * @return conditions
  **/
  @ApiModelProperty(value = "")
  public ConditionGroupUpdate getConditions() {
    return conditions;
  }

  public void setConditions(ConditionGroupUpdate conditions) {
    this.conditions = conditions;
  }

  public TransitionUpdateDTO customIssueEventId(String customIssueEventId) {
    this.customIssueEventId = customIssueEventId;
    return this;
  }

   /**
   * The custom event ID of the transition.
   * @return customIssueEventId
  **/
  @ApiModelProperty(value = "The custom event ID of the transition.")
  public String getCustomIssueEventId() {
    return customIssueEventId;
  }

  public void setCustomIssueEventId(String customIssueEventId) {
    this.customIssueEventId = customIssueEventId;
  }

  public TransitionUpdateDTO description(String description) {
    this.description = description;
    return this;
  }

   /**
   * The description of the transition.
   * @return description
  **/
  @ApiModelProperty(value = "The description of the transition.")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public TransitionUpdateDTO id(String id) {
    this.id = id;
    return this;
  }

   /**
   * The ID of the transition.
   * @return id
  **/
  @ApiModelProperty(value = "The ID of the transition.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public TransitionUpdateDTO links(List<WorkflowTransitionLinks> links) {
    this.links = links;
    return this;
  }

  public TransitionUpdateDTO addLinksItem(WorkflowTransitionLinks linksItem) {
    if (this.links == null) {
      this.links = new ArrayList<>();
    }
    this.links.add(linksItem);
    return this;
  }

   /**
   * The statuses the transition can start from, and the mapping of ports between the statuses.
   * @return links
  **/
  @ApiModelProperty(value = "The statuses the transition can start from, and the mapping of ports between the statuses.")
  public List<WorkflowTransitionLinks> getLinks() {
    return links;
  }

  public void setLinks(List<WorkflowTransitionLinks> links) {
    this.links = links;
  }

  public TransitionUpdateDTO name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The name of the transition.
   * @return name
  **/
  @ApiModelProperty(value = "The name of the transition.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public TransitionUpdateDTO properties(Map<String, String> properties) {
    this.properties = properties;
    return this;
  }

  public TransitionUpdateDTO putPropertiesItem(String key, String propertiesItem) {
    if (this.properties == null) {
      this.properties = new HashMap<>();
    }
    this.properties.put(key, propertiesItem);
    return this;
  }

   /**
   * The properties of the transition.
   * @return properties
  **/
  @ApiModelProperty(value = "The properties of the transition.")
  public Map<String, String> getProperties() {
    return properties;
  }

  public void setProperties(Map<String, String> properties) {
    this.properties = properties;
  }

  public TransitionUpdateDTO toStatusReference(String toStatusReference) {
    this.toStatusReference = toStatusReference;
    return this;
  }

   /**
   * The status the transition goes to.
   * @return toStatusReference
  **/
  @ApiModelProperty(value = "The status the transition goes to.")
  public String getToStatusReference() {
    return toStatusReference;
  }

  public void setToStatusReference(String toStatusReference) {
    this.toStatusReference = toStatusReference;
  }

  public TransitionUpdateDTO transitionScreen(WorkflowRuleConfiguration transitionScreen) {
    this.transitionScreen = transitionScreen;
    return this;
  }

   /**
   * Get transitionScreen
   * @return transitionScreen
  **/
  @ApiModelProperty(value = "")
  public WorkflowRuleConfiguration getTransitionScreen() {
    return transitionScreen;
  }

  public void setTransitionScreen(WorkflowRuleConfiguration transitionScreen) {
    this.transitionScreen = transitionScreen;
  }

  public TransitionUpdateDTO triggers(List<WorkflowTrigger> triggers) {
    this.triggers = triggers;
    return this;
  }

  public TransitionUpdateDTO addTriggersItem(WorkflowTrigger triggersItem) {
    if (this.triggers == null) {
      this.triggers = new ArrayList<>();
    }
    this.triggers.add(triggersItem);
    return this;
  }

   /**
   * The triggers of the transition.
   * @return triggers
  **/
  @ApiModelProperty(value = "The triggers of the transition.")
  public List<WorkflowTrigger> getTriggers() {
    return triggers;
  }

  public void setTriggers(List<WorkflowTrigger> triggers) {
    this.triggers = triggers;
  }

  public TransitionUpdateDTO type(TypeEnum type) {
    this.type = type;
    return this;
  }

   /**
   * The transition type.
   * @return type
  **/
  @ApiModelProperty(value = "The transition type.")
  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }

  public TransitionUpdateDTO validators(List<WorkflowRuleConfiguration> validators) {
    this.validators = validators;
    return this;
  }

  public TransitionUpdateDTO addValidatorsItem(WorkflowRuleConfiguration validatorsItem) {
    if (this.validators == null) {
      this.validators = new ArrayList<>();
    }
    this.validators.add(validatorsItem);
    return this;
  }

   /**
   * The validators of the transition.
   * @return validators
  **/
  @ApiModelProperty(value = "The validators of the transition.")
  public List<WorkflowRuleConfiguration> getValidators() {
    return validators;
  }

  public void setValidators(List<WorkflowRuleConfiguration> validators) {
    this.validators = validators;
  }


  @com.fasterxml.jackson.annotation.JsonAnyGetter
  public Map<String, Object> any() {
   return this.additionalProperties_;
  }

  @com.fasterxml.jackson.annotation.JsonAnySetter
  public void set(String name, Object value) {
   this.additionalProperties_.put(name, value);
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransitionUpdateDTO transitionUpdateDTO = (TransitionUpdateDTO) o;
    return Objects.equals(this.actions, transitionUpdateDTO.actions) &&
        Objects.equals(this.conditions, transitionUpdateDTO.conditions) &&
        Objects.equals(this.customIssueEventId, transitionUpdateDTO.customIssueEventId) &&
        Objects.equals(this.description, transitionUpdateDTO.description) &&
        Objects.equals(this.id, transitionUpdateDTO.id) &&
        Objects.equals(this.links, transitionUpdateDTO.links) &&
        Objects.equals(this.name, transitionUpdateDTO.name) &&
        Objects.equals(this.properties, transitionUpdateDTO.properties) &&
        Objects.equals(this.toStatusReference, transitionUpdateDTO.toStatusReference) &&
        Objects.equals(this.transitionScreen, transitionUpdateDTO.transitionScreen) &&
        Objects.equals(this.triggers, transitionUpdateDTO.triggers) &&
        Objects.equals(this.type, transitionUpdateDTO.type) &&
        Objects.equals(this.validators, transitionUpdateDTO.validators) &&
        super.equals(o);
  }

  @Override
  public int hashCode() {
    return Objects.hash(actions, conditions, customIssueEventId, description, id, links, name, properties, toStatusReference, transitionScreen, triggers, type, validators, super.hashCode());
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransitionUpdateDTO {\n");
    
    sb.append("    actions: ").append(toIndentedString(actions)).append("\n");
    sb.append("    conditions: ").append(toIndentedString(conditions)).append("\n");
    sb.append("    customIssueEventId: ").append(toIndentedString(customIssueEventId)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    links: ").append(toIndentedString(links)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("    toStatusReference: ").append(toIndentedString(toStatusReference)).append("\n");
    sb.append("    transitionScreen: ").append(toIndentedString(transitionScreen)).append("\n");
    sb.append("    triggers: ").append(toIndentedString(triggers)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    validators: ").append(toIndentedString(validators)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties_)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

